### ISSUE TITLE
@Parameter is giving java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by raghung** [micronaut-projects/micronaut-openapi#25] opened 2019-06-02 21:47 UTC
Version tested: 1.1.2

Controller:
import io.micronaut.http.MediaType
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.reactivex.Single
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.tags.Tag

import javax.validation.constraints.NotBlank

@Tag(name = "Test")
@Controller("/test")
class TestController {

    /**
     * @param name Name of the person
     * @return Greetings message
     */
    @Get(uri="/greetings/{name}", produces= MediaType.TEXT_PLAIN)
    @Operation(summary = "Greets a person",
            description = "A friendly greeting is returned"
    )
    @ApiResponse(
            content = @Content(mediaType = MediaType.TEXT_PLAIN,
                               schema = @Schema(type="string"))
    )
    @ApiResponse(responseCode = "400", description = "Invalid Name Supplied")
    @ApiResponse(responseCode = "404", description = "Person not found")
    Single<String> greetings(@Parameter(description = "Name of the person") @NotBlank String name) {
        return Single.just("Hello $name, How are you doing?")
    }
}

**Comment by gregratliff** [comment] 2019-06-02 21:59
I believe that the issue is that the `AnnotationMetadataWriter `is using the enum value's `toString()` method rather than the `name()` method when generating the `AnnotationMetadata`.  If you look at the generated AnnotationMetadata class for your controller, you will see that the in field value is lower case rather than upper case. 

I believe that the following code change will fix the issue:

File: in subproject inject, `io/micronaut/inject/annotation/AnnotationMetadataWriter.java` ~line 440  (the Enum case of the if/else if logic)
OLD:  `methodVisitor.getStatic(t, value.toString(), t);`
NEW: `methodVisitor.getStatic(t, enumObject.name(), t);`

**Comment by gregratliff** [comment] 2019-06-02 22:08
@raghung, I think this is an issue with the generation of the annotation metadata which is part of the micronaut-core project.  If you open this issue in the micronaut-core project, I will create a pull-request with the fix.

**Comment by raghung** [comment] 2019-06-02 22:35
@gregratliff, I have logged the issue in micronaut-core project(https://github.com/micronaut-projects/micronaut-core/issues/1739)

**Comment by gregratliff** [comment] 2019-06-03 13:55
This issue should be closed.  It has been resolved in micronaut-core (micronaut-projects/micronaut-core#1739)

**Closed** 2019-06-03 14:09 UTC
