### ISSUE TITLE
When a field has @field:Schema annotation, it is not listed as required

### ISSUE THREAD

**Issue by ruiminamywang** [micronaut-projects/micronaut-openapi#643] opened 2022-01-14 18:12 UTC
### Expected Behavior

With micronaut 2.5.13, micronaut-openapi 2.6.2, language: Kotlin
```
@Introspected
data class SomeRequest(
    @field:Schema(description = "description ...")
    @field:NotBlank
    val name: String,
    @field:Schema(description = "description ...")
    val description: String? // Optional
)
```
The code above generates openAPI specs like
```
    SomeRequest:
      required:
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: description ...
        description:
          type: string
          description: description ...
          nullable: true
```

### Actual Behaviour

However, after upgrading to micronaut 3.1.4, and micronaut-openapi 3.2.0, `name` become optional after auto-generating the openAPI specs:
```
    SomeRequest:
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: description ...
        description:
          type: string
          description: description ...
          nullable: true
```

These lines are removed
```
      required:
      - name
```

### Steps To Reproduce

1. Use micronaut 3.1.4, and micronaut-openapi 3.2.0
2. Use the following data class
```
@Introspected
data class SomeRequest(
    @field:Schema(description = "description ...")
    @field:NotBlank
    val name: String,
    @field:Schema(description = "description ...")
    val description: String? // Optional
)
```
3. generate the openapi yaml file

### Version

micronaut 3.1.4, and micronaut-openapi 3.2.0

**Comment by eratio08** [comment] 2022-01-18 15:11
Experiencing the same issue.
Removing the `@field:Schema` annotation from the field brings back `required` in the spec - but this is not a suitable workaround.

**Comment by ilopmar** [comment] 2022-01-18 15:14
This is a known issue with Kotlin data classes and a duplicate of #611. Please read that issue and the solution (once we release a new version of micronaut-openapi).

**Closed by ilopmar** 2022-01-18 15:14 UTC
Labels: closed: duplicate

**Comment by xzhang-brex** [comment] 2022-01-26 21:14
@ilopmar hi, could you confirm this is fixed? as this issue seems a bit different than https://github.com/micronaut-projects/micronaut-openapi/issues/611

**Comment by eratio08** [comment] 2022-01-27 06:36
@xzhang-brex well it's not really different, the thing here is, if you use `@Schema` on a non-nullable field make sure you set the `required` prop of the annotation to `true`. It comes down to this property beeing `false` by default and it overrides the kotlin non-nullability.

**Comment by ilopmar** [comment] 2022-01-27 07:37
Thanks @xzhang-brex for the explanaition :+1: 

The issue is fixed and included in release `v4.0.0` that will be part of Micronaut 3.3.0 by default. If you want to use it now, just force that version of the dependency.

**Comment by xzhang-brex** [comment] 2022-01-27 14:11
@ilopmar i guess you wanted to thank @eratio08 ? (Cuz I didn't explain anything..)

With 4.0.0, do I still need to add required = true to @Schema on a non-nullable field?

**Comment by ilopmar** [comment] 2022-01-27 14:36
Yes, you are right :sweat:. Thanks @eratio08  :-)

With 4.0.0 you need to annotate the fields with `@field:Schema(nullable = false, required = true)`

**Comment by xzhang-brex** [comment] 2022-01-27 14:44
@ilopmar so basically if we use @Schema, micronaut will take it as the highest priority and will ignore the null-ability of the field being annotated, is that the current design philosophy?

If so, then the issue mentioned in this post is not an issue anymore, it is something expected..

**Comment by ilopmar** [comment] 2022-01-27 14:51
In Micronaut OpenAPI the Swagger annotations will always take precedence over any other annotation. If that doesn't happen, then it's probably a bug.
In this case the problem is because of Kotlin and data classes. With Java everything works as expected.

**Comment by xzhang-brex** [comment] 2022-01-27 15:21
@ilopmar sorry for the confusion.

The issue described in this post is: When using @Schema (without adding required = true) on a non-nullable field, the field will be removed from required list in generated openapi spec.

If I understand your and @eratio08  comments correctly, this is expected behavior because **required** is **false** by default in @Schema, and micronaut will honor that **false** value, regardless the type is **String?** or **String**."

If so, the issue in this post is no longer an issue as it is expected behavior.

Am I right?
