### ISSUE TITLE
OpenAPI property name results in incorrect method generation 2

### ISSUE THREAD

**Issue by CezaryBD** [micronaut-projects/micronaut-openapi#1449] opened 2024-02-21 13:36 UTC
### Expected Behavior

Based on this example: https://guides.micronaut.io/latest/micronaut-openapi-generator-client-gradle-java.html

I expect to have getters and setters working and returning passed values.

### Actual Behaviour

I get null pointers.

### Steps To Reproduce

Run the included test and see that getter is invoked on null (although the value is set in the JSON file).

### Environment Information

MacOS Sonoma 14.2.1
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)

Micronaut plugins version: 4.2.1

### Example Application

https://github.com/CezaryBD/reproducible-micronaut-openapi-casing-problem-02

### Version

4.2.4

**Comment by pinarodrigo** [comment] 2024-02-21 13:52
I am experiencing the same in my project.

Any workaround?

**Comment by CezaryBD** [comment] 2024-02-22 10:16
Hello @sdelamo @altro3. Why are the enums being focused instead of property with underscore __default_? Am I missing something?

**Comment by altro3** [comment] 2024-02-22 10:56
@CezaryBD Please explain more clearly what is wrong. I'm afraid I don't understand what you're talking about.

**Comment by CezaryBD** [comment] 2024-02-22 10:59
> @CezaryBD Please explain more clearly what is wrong. I'm afraid I don't understand what you're talking about.

Property starting with underscore is not de-serialized correctly, thus resulting in the getter returning null. Similar to: https://github.com/micronaut-projects/micronaut-openapi/issues/1226

**Comment by altro3** [comment] 2024-02-22 11:07
You don't have to be like us and generate JsonCreator and JsonValue anonymization. In addition, it is not necessary to set the JSON property, regardless of whether EnumConstant is required.

You cannot name an enumeration of constants reserved by words or by numbers. Example, if `allowedValues: [1, 2, 3, 4]`, then you can's create enum like this:
```java
enum MyEnum{
    1, 2,  3, 4;
}
```
you need to wrap them like this:
```java
enum MyEnum{
    _1(1),
    _2(2),
    _3(3),
    _4(4);

    private final int value;

....
}
```

The same with other reserved words.

But, to be clear, the formation of the name enum const takes place at the level of the library `openapigenerator'. I think this is a standard strategy inside the `org.openapitools.codegen.languages.AbstractJavaCodegen` class

**Comment by altro3** [comment] 2024-02-22 11:09
`default` - is reserved word in java, like a `switch`, `if` and other

**Comment by altro3** [comment] 2024-02-22 11:12
If deseralization doesn't work for you, then you need to find out why it happens. Because `JsonValue`, `JsonCreator` and `JsonProperty` annotations should be enough (I've been using them for about 10 years)

**Comment by altro3** [comment] 2024-02-22 11:20
@CezaryBD JSYK  I found some more problems in enum generator today for kotlin and java. I fixed them here: https://github.com/micronaut-projects/micronaut-openapi/pull/1451

This screenshot illustrates this bug on your sample project:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/b1cbbf21-6e7d-4ebb-b1e3-6c75852e0f64)

As you see, method `fromValue` has `String` parameter, but must be `Integer`. 

But, in general, the problem is only with non-string enums.

**Comment by altro3** [comment] 2024-02-22 11:25
@CezaryBD Did I answer your question?

**Comment by altro3** [comment] 2024-02-22 12:15
Interestingly, you wrote about one problem, but I found another problem with enums and fixed it :-)

**Comment by CezaryBD** [comment] 2024-02-22 12:17
> Interestingly, you wrote about one problem, but I found another problem with enums and fixed it :-)

I must say, I find it quite interesting too haha. Thank you very much!

**Comment by CezaryBD** [comment] 2024-02-22 12:29
Then I guess we will need to tackle this with them, right?

**Comment by altro3** [comment] 2024-02-22 12:40
Well, you can write to them about it, but you need confirmation using their java generator. After all, we use our own msutache templates and our own generator.

Well, I'll fix it for micronaut-openapi for now :-)

This is not the first bug that is present in openapigeenrator, and which I fixed only for myronaut

**Closed** 2024-02-22 13:53 UTC

**Comment by altro3** [comment] 2024-02-23 06:34
Now all works fine. Try to use latest version - `6.6.2`:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/a2421f0e-425e-4b4b-8f68-ac5960de0c75)
Also, you can use a faster solution to the problem with naming getters and setters than waiting for me to fix the problem.
Just turn on lombok in the generator, then getters and setters will be generated by lombok, and not by the openapi generator
