### ISSUE TITLE
Generated OpenAPI is having wrong key

### ISSUE THREAD

**Issue by Poorva17** [micronaut-projects/micronaut-openapi#635] opened 2021-12-30 06:20 UTC
### Expected Behavior

When request / response body has parameter prefixed with `is`, its wrongly put in generated openAPI yml.

For example, 
pseudo request body (**Expected**)
{
     "name: "string",
      "address": "string",
      "**isPrimary**": "Boolean"
}

### Actual Behaviour

For example, 
pseudo request body (**Actual**)
{
     "name: "string",
      "address": "string",
      "**primary**": "Boolean" // this is expected as `isPrimary` but it's getting generated as `primary`
}

### Environment Information

- mac os 
- openjdk version "11.0.10" 2021-01-19

kapt("io.micronaut.configuration:micronaut-openapi:1.5.2")
implementation("io.swagger.core.v3:swagger-annotations:2.1.3")

### Version

1.5.2

**Comment by ilopmar** [comment] 2022-01-03 11:41
Duplicate of #616

**Closed by ilopmar** 2022-01-03 11:42 UTC
Labels: closed: duplicate
