### ISSUE TITLE
OpenAPI Generator always generates the `@JsonTypeInfo` annotation without the `visible` property in models for Micronaut Serialization

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-openapi#1273] opened 2023-11-03 09:15 UTC
### Expected Behavior

**_IMPORTANT!!!_** The fix for this issue should not be released, before the fix of Micronaut Serialization to support the `visible` property for the `@JsonTypeInfo` annotation. This was fixed today (3rd Nov 2023) in [this issue](https://github.com/micronaut-projects/micronaut-serialization/issues/581). 

I expect the OpenAPI Generator to generate the `@JsonTypeInfo` annotation so it is identical for Jackson and Micronaut Serialization. So if a `visible` property is generated for Jackson, it should also be generated for Micronaut Serialization.

### Actual Behaviour

The `visible` property is never generated for the `@JsonTypeInfo` annotation in models for Micronaut Serialization.

### Steps To Reproduce

1. Clone the repository https://github.com/runenielsen/mn-discriminator-null-serde-bug, that uses Micronaut Serialization.
2. Run the `testPostModelWithDiscriminator` test case in `BookInfoControllerTest` to post the model with a discriminator to a service endpoint with validation.
3. See that the test fails due to a validation failure "bookInfo.type: must not be null".
4. Inspect the generated `BookInfo` model in `generateServerOpenApiModels`and see that the `@JsonTypeInfo` annotation looks like this: `@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")`
5. To run the test with the correct model, comment in the code under `/* Comment this in to run with the visible property set to true as in the generated models for Jackson.` in `build.gradle.kts`. Notice this currently gives this error due to `visible` not being supported in Micronaut Serialization: `/Users/rune.nielsen/projects/mn-discriminator-null-serde-bug/build/generated/openapi/generateServerOpenApiModels/src/main/java/com/example/openapi/server/model/BookInfo.java:50: error: Annotation @JsonTypeInfo specifies attribute 'visible'. Currently supported attributes include: [include, use, property, defaultImpl] public class BookInfo {`. This is why the fix here should not be released before the fix already done in [this issue](https://github.com/micronaut-projects/micronaut-serialization/issues/581).
7. Now clone the repository https://github.com/runenielsen/mn-discriminator-not-null-with-jackson, that contains the same code, but uses Jackson Databind instead of Micronaut Serialization.
8. See that the same test succeeds in that repository.
9. Inspect the generated `BookInfo` model in `generateServerOpenApiModels`and see that the `@JsonTypeInfo` annotation looks like this: `@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true)`

### Environment Information

- macOS
- JDK 17 (Temurin)

### Example Applications

https://github.com/runenielsen/mn-discriminator-null-serde-bug and https://github.com/runenielsen/mn-discriminator-not-null-with-jackson

### Version

4.1.6

**Comment by altro3** [comment] 2023-11-03 12:01
@runenielsen Sorry, I don’t quite understand how to fix the generator if the problem is in micronaut serialization? Those. What is being generated incorrectly now?

**Comment by altro3** [comment] 2023-11-03 12:08
@runenielsen Could you tell me what is wrong in generator now, because release 5.2.0 approved and I can release all other changes

**Comment by altro3** [comment] 2023-11-03 12:22
@runenielsen could you check this PR https://github.com/micronaut-projects/micronaut-openapi/pull/1274 ? is it rigth solution?

**Comment by runenielsen** [comment] 2023-11-03 12:36
Hi @altro3.

Thanks. I will take a look.

I'm not entirely sure you should always add `visible = true` - I'm guessing, it should work exactly the same way as for Jackson.

So:

- if `visible = true` is added when generating Jackson models, `visible = true` should also be added when generating Micronaut Serialization models.
- if `visible = false` is added when generating Jackson models, `visible = false` should also be added when generating Micronaut Serialization models.
- if `visible` is NOT added when generating Jackson models, it also not be added when generating Micronaut Serialization models.

**Comment by runenielsen** [comment] 2023-11-03 12:39
Alright, it looks like `visible = true` is always added for Jackson in your PR, so it must be correct to also always add it for Micronaut Serialization.

So I agree with the change in your PR, thanks for quick work as always! 🙂

**Comment by altro3** [comment] 2023-11-03 13:09
One moment: now this flag will add in any case. You can change value to `false`. Is it right behavior? Or we need add ability to set `false` for user?

**Comment by altro3** [comment] 2023-11-03 13:14
anyway I published release 5.2.0 and this fix will be in release 5.2.1, when micronaut-serialization will be published

**Comment by runenielsen** [comment] 2023-11-03 13:20
@altro3 : I don't quite understand your question...

Anyway, my opinion is that it should work exactly the same for Jackson and Serde, so there is no ability to set it to `false` for Jackson (which looks to be the case based on your PR), there doesn't need to be for Serde either...

**Comment by altro3** [comment] 2023-11-03 13:26
Yes, I agree that it is not right for them to work differently, but the question was specifically about the possibility of specifying false for this parameter, because now it is always set to true . Noah himself already realized that this is correct behavior, because... We have a discriminator field in each subclass

**Closed** 2023-11-14 09:29 UTC
