### ISSUE TITLE
Wrong schema generation while using inheritance

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-openapi#347] opened 2020-09-23 14:05 UTC
It seems to be that the schema is wrong while using inheritance:

```
@Introspected
@Schema(allOf = CoreDomainTracking.class)
public abstract class BrochurePageTracking extends CoreDomainTracking {
  ...
}
```

```
    BrochurePageTracking:
      allOf:
      - $ref: '#/components/schemas/CoreDomainTracking'
      - required:
        - brochurePage
        type: object
        properties:
          brochurePage:
            maximum: 999
            minimum: 1
            type: integer
            description: The page of the brochure.
            format: int32
```

If i understand correctly, the `required:` can't have a leading ` - ` and all the code below needs to move to left.

The last version of micronaut 1.x generated a correct scheme like:

```
    BrochurePageTracking:
      required:
      - brochurePage
      type: object
      properties:
        brochurePage:
          maximum: 999
          minimum: 1
          type: integer
          description: The page of the brochure.
          format: int32
      allOf:
      - $ref: '#/components/schemas/CoreDomainTracking'
```

**Comment by alphawolf1988** [comment] 2020-09-23 14:09
There was already a fix for this problem: #117 but now it occurs again.

**Comment by asodja** [comment] 2021-05-01 10:35
It looks like that is correct Schema according to: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ for OpenApi 3.0.

Check:
```
ExtendedErrorModel:
  allOf:     # Combines the BasicErrorModel and the inline model
    - $ref: '#/components/schemas/BasicErrorModel'
    - type: object
      required:
        - rootCause
      properties:
        rootCause:
          type: string
 ```
 
 which is equal to:
 ```
ExtendedErrorModel:
  allOf:     # Combines the BasicErrorModel and the inline model
    - $ref: '#/components/schemas/BasicErrorModel'
    - required:
        - rootCause
      type: object
      properties:
        rootCause:
          type: string
   ```
 
You can translate yaml to json and you can see, that this is the same, only order of elements is different. But order does not matter.

**Comment by ilopmar** [comment] 2021-08-19 15:43
I've tried with the following code and Micronaut 3.0.0:

```java
@Introspected
public class CoreDomainTracking {

    private String coreProperty;

    public CoreDomainTracking(String coreProperty) {
        this.coreProperty = coreProperty;
    }

    public String getCoreProperty() {
        return coreProperty;
    }

    public void setCoreProperty(String coreProperty) {
        this.coreProperty = coreProperty;
    }
}
```

```java
@Introspected
@Schema(allOf = CoreDomainTracking.class)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public abstract class BrochurePageTracking extends CoreDomainTracking {

    private Integer brochurePage;

    public BrochurePageTracking(String coreProperty, Integer brochurePage) {
        super(coreProperty);
        this.brochurePage = brochurePage;
    }

    public Integer getBrochurePage() {
        return brochurePage;
    }

    public void setBrochurePage(Integer brochurePage) {
        this.brochurePage = brochurePage;
    }
}
```

```java
@Controller("/")
public class FooController {

    @Get("/foo")
    public void foo(BrochurePageTracking brochurePageTracking) {
    }
}
```

And it generates:

```yaml
openapi: 3.0.1
info:
  title: openapi-347
  version: "0.0"
paths:
  /foo:
    get:
      operationId: foo
      parameters:
      - name: brochurePageTracking
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/BrochurePageTracking'
      responses:
        "200":
          description: foo 200 response
components:
  schemas:
    BrochurePageTracking:
      allOf:
      - $ref: '#/components/schemas/CoreDomainTracking'
      - required:
        - brochurePage
        type: object
        properties:
          brochurePage:
            type: integer
            format: int32
    CoreDomainTracking:
      required:
      - coreProperty
      type: object
      properties:
        coreProperty:
          type: string
```

And it is a valid openapi definition:

![image](https://user-images.githubusercontent.com/559192/130099303-35b014eb-d36a-4f7b-b7e6-9facc048981b.png)


@alphawolf1988 if you can provide an application that reproduces the problem I'll take a look. Otherwise I'll close the issue in a few days.

**Comment by ilopmar** [comment] 2021-09-08 11:20
Closed due to the lack of feedback. If the problem still happens, please file a new issue with an application that reproduces the problem.

**Closed by ilopmar** 2021-09-08 11:20 UTC
Labels: status: awaiting feedback, type: bug
