### ISSUE TITLE
OpenAPI doc generation fails, when customising the return type content.

### ISSUE THREAD

**Issue by sven1103** [micronaut-projects/micronaut-openapi#23] opened 2019-05-28 11:10 UTC
Dear all, 

I am currently struggling with the automated OpenAPI doc generation on my Micronaut project, when customising the response documentation of an GET endpoint with the `@ApiResponse` annotation.

Example:

```java
@Log4j2
@Controller("/workflows")
class MessagesController {
    ...
    @Get("/traces/{runId}")
    @ApiResponse(
            responseCode = "200",
            description = "Simple trace object",
            content = @Content(
                    mediaType = "application/json",
                    schema = @Schema(implementation = Trace.class)
            ))
    HttpResponse<Trace> getTracesForWorkflow(String runId) {
        log.debug("Traces request for runId: $runId.")
        List<Trace> traces
        try {
            traces = informationCenter.getTracesForWorkflowWithId(runId)
        } catch ( Exception e) {
            log.error(e)
            return HttpResponse.serverError("Unexpected error.")
        }
        return HttpResponse.ok(traces.get(0))
    }
```

**Expected behaviour**

Successful Generation of the OpenAPI documentation, with the endpoint response type description that references to a schema representing the `Trace.class`.

**Observed behaviour**

Maven goal `compile` fails, using the maven compiler plugin.

```bash
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ nxflogger ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
Note: Generating OpenAPI Documentation
WARNING: Error reading Swagger ApiResponses for element [io.micronaut.ast.groovy.visitor.GroovyMethodElement@32431a9c]: Cannot construct instance of `io.swagger.v3.oas.models.media.MediaType` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('application/json')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.responses.ApiResponse["content"]->io.swagger.v3.oas.models.media.Content["mediaType"])

       @Get("/traces/{runId}")
       ^
Note: Writing OpenAPI YAML to destination: file:/Users/sven1103/git/nxflogger/target/classes/META-INF/swagger/flowstore-0.1.yml
```

### System and build environment

Micronaut: 1.1.2
io.swagger.core.v3.swagger-models: 2.0.8
io.swagger.core.v3.swagger-annotations: 2.0.8

io.micronaut.configuration.micronaut-openapi scope set to `provided`.

```
> mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_181, vendor: Azul Systems, Inc., runtime: /Users/sven1103/.sdkman/candidates/java/8.0.181-zulu/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
```

Thanks a lot for any hints, help or advice. 

Best, Sven

**Comment by puneetbehl** [comment] 2019-07-07 00:31
I have been very busy lately so could not make any progress on this.

**Comment by JacobAae** [comment] 2019-08-16 09:07
Looking into this, I have found that the problem is specific for Groovy, as the same annotations work for a Micronaut java project. In `AbstractOpneApiVisitor.bindSchemaIfNeccessary` the schema is tried based on the classElement found from the context.

* In the Java project, the context is of type ` io.micronaut.annotation.processing.visitor.JavaVisitorContext` and the call to `context.getClassElement(className)` locates classes referenced in the Schema annotation correctly. 
* In a Groovy project, the context is of type `io.micronaut.ast.groovy.visitor.GroovyVisitorContext` and the call to `context.getClassElement(className)` responds with an empty optional, and this causes the mapping to be wrong. 

I thus believe the issue is in the `GroovyVisitorContext`, but I have not found the time to look deeper into this. Hopefully someone with better classloader knowledge than me can help from here.

**Comment by puneetbehl** [comment] 2019-11-11 19:35
I think it should work when you define content as an array in the `ApiReponse` annotation as:

```
    @ApiResponse(
            responseCode = "200",
            description = "Simple trace object",
            content = [@Content(
                    mediaType = "application/json",
                    schema = @Schema(implementation = Trace.class)
            )]
    )
```

For some reason, while reading the `AnnotationValue` it is not converting content into an array in case of Groovy. I am working on this and will share the fix soon.

**Comment by sven1103** [comment] 2019-11-12 09:24
Thank you @puneetbehl for looking into this!

**Comment by puneetbehl** [comment] 2019-11-20 15:20
This issue will be resolved once the PR micronaut-projects/micronaut-core#2374 is merged and Micronaut v1.2.7 is released.

**Comment by virtutemRob** [comment] 2019-11-22 16:09
Excited to see this resolved.  Thank you @puneetbehl!

**Comment by sven1103** [comment] 2019-12-10 11:37
@puneetbehl Thank you so much, I can confirm that it works now with Micronaut 1.2.7.

**Closed** 2019-12-10 11:37 UTC
Labels: info: workaround available, relates-to: micronaut-core
