### ISSUE TITLE
Duplicated properties from inheritance using micronaut v3 (groovy)

### ISSUE THREAD

**Issue by paulosantama** [micronaut-projects/micronaut-openapi#670] opened 2022-03-04 15:58 UTC
### Expected Behavior

When using inheritance (with allOf referencing the parent), the expected behavior is:

- the child's schema referencing through 'allOf' its parent
- the parent's properties omitted in child schema

### Example:
```
@Introspected
@CompileStatic
@Schema(
		name = 'Entidade'
)
abstract class EntidadeDto {

	@NotNull
	UUID id

	Long tenantId

	Integer version

	@NotNull
	Date criadoEm

	@NotNull
	Date atualizadoEm

}
```
```
@Introspected
@CompileStatic
@Schema(
		name = 'PessoaFisica',
		allOf = [EntidadeDto]
)
class PessoaFisicaDto extends EntidadeDto {

	String nome

	String nomeMae

	String nomePai

	String CPF

}
```
generates:
```
Entidade:
  required:
  - atualizadoEm
  - criadoEm
  - id
  type: object
  properties:
    id:
      type: string
      format: uuid
    tenantId:
      type: integer
      format: int64
    version:
      type: integer
      format: int32
    criadoEm:
      type: string
      format: date-time
    atualizadoEm:
      type: string
      format: date-time
PessoaFisica:
  allOf:
  - $ref: '#/components/schemas/Entidade'
  - type: object
    properties:
      nome:
        type: string
      nomeMae:
        type: string
      nomePai:
        type: string
      CPF:
        type: string
```

### Actual Behaviour

When using micronaut v2 and groovy, it is OK! But when using micronaut v3 with groovy, we have a problem, the following happens:

- the child's schema referencing through 'allOf' its parent
- the parent's properties aren't omitted in child schema

generates:
```
Entidade:
  required:
  - atualizadoEm
  - criadoEm
  - id
  type: object
  properties:
    id:
      type: string
      format: uuid
    tenantId:
      type: integer
      format: int64
    version:
      type: integer
      format: int32
    criadoEm:
      type: string
      format: date-time
    atualizadoEm:
      type: string
      format: date-time
PessoaFisica:
  allOf:
  - $ref: '#/components/schemas/Entidade'
  - required:
    - atualizadoEm
    - criadoEm
    - id
    type: object
    properties:
      nome:
        type: string
      nomeMae:
        type: string
      nomePai:
        type: string
      CPF:
        type: string
      id:
        type: string
        format: uuid
      tenantId:
        type: integer
        format: int64
      version:
        type: integer
        format: int32
      criadoEm:
        type: string
        format: date-time
      atualizadoEm:
        type: string
        format: date-time
```

I noticed that using java, it works good, so I had been transforming java code in groovy code, until found the error. When using micronaut v2, micronaut-openapi recognize properties's implicit getters and setters from groovy. But when using micronaut v3 it doesn't recognize. To make it works, I needed change the parent's properties to `private` and make explicit getters and setters, like java code.

changes:
```
@Introspected
@CompileStatic
@Schema(
		name = 'Entidade'
)
abstract class EntidadeDto {

	@NotNull
	private UUID id

	private Long tenantId

	private Integer version

	@NotNull
	private Date criadoEm

	@NotNull
	private Date atualizadoEm

	UUID getId() {
		return id
	}

	void setId(UUID id) {
		this.id = id
	}

	Long getTenantId() {
		return tenantId
	}

	void setTenantId(Long tenantId) {
		this.tenantId = tenantId
	}

	Integer getVersion() {
		return version
	}

	void setVersion(Integer version) {
		this.version = version
	}

	Date getCriadoEm() {
		return criadoEm
	}

	void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm
	}

	Date getAtualizadoEm() {
		return atualizadoEm
	}

	void setAtualizadoEm(Date atualizadoEm) {
		this.atualizadoEm = atualizadoEm
	}

}
```

Then, it generates the expected.

### Steps To Reproduce

clone the git repository: [repository](https://github.com/paulosantama/openapi-micronaut3)

branchs:
- `master`: where the problem occurs using micronaut v3
- `micronaut-2`: where the problem doesn't occurs using micronaut v2
- `micronaut-3`: where changes was do to it to works using micronaut v3

steps:
- using `micronaut-2`, compile the code and see that it generates the correct yaml
- using `master`, compile the code and see that it doesn't generates the correct yaml
- using `micronaut-3`, compile the code and see that it generates the correct yaml using micronaut v3

### Environment Information

JDK 11
groovy 3.0.9

### Example Application

https://github.com/paulosantama/openapi-micronaut3

### Version

micronaut-openapi 3.1.0
micronaut 3.1.4

**Comment by altro3** [comment] 2022-09-25 14:48
@paulosantama Hi! I found what the problem is. The error, indeed, occurs only when working with grooves. I fixed the problem in the kernel, as soon as my changes go into release, the problem will be fixed in micronaut-openapi

**Closed** 2022-10-04 10:17 UTC
