### ISSUE TITLE
Swagger UI not generated using KSP

### ISSUE THREAD

**Issue by liefra** [micronaut-projects/micronaut-openapi#1154] opened 2023-08-01 05:15 UTC
### Expected Behavior

The Swagger UI views are being generated successfully when `swagger-ui.enabled=true`

### Actual Behaviour

No Swagger UI views are available resulting in a 404 error.

Please note that this error does only occur using Kotlin and KSP. 

It does not occur when using Kotlin and Kapt and also not when using Java.

### Steps To Reproduce

Generate an [Kotlin app using Micronaut launch with openapi and swagger ui enabled](https://micronaut.io/launch?type=DEFAULT&name=swaggeruidemo&package=com.example&javaVersion=JDK_17&lang=KOTLIN&build=GRADLE_KOTLIN&test=SPOCK&features=swagger-ui&features=openapi&version=4.0.2) 

Run it and try to access http://localhost:8080/swagger-ui#/default/index

NOTE: When you enable KAPT instead of KSP it works as expected.

### Environment Information

- JDK 17
- Kotlin
- Mac OS

### Version

4.0.2

**Comment by altro3** [comment] 2023-08-03 13:26
@liefra Hi! hm... I tested this issue with version 5.0.2-SNAPSHOT and found 3 bugs in micronaut-ksp (in core module) - https://github.com/micronaut-projects/micronaut-core/issues/9671, https://github.com/micronaut-projects/micronaut-core/issues/9672, https://github.com/micronaut-projects/micronaut-core/issues/9670

Need to wait when these bugs will be fixed.

**Comment by thalesdev** [comment] 2023-08-16 17:43
@altro3 Hi! I saw that these issues were closed I tried here with `micronaut-core 4.0.4` and `micronaut-openapi 5.1.0` however I still got the same problem. Is there any way around this? I wanted to migrate my project from kapt to ksp.

**Comment by nbrugger-tgm** [comment] 2023-08-16 22:26
I have a similar if not the same issue using micronaut 3.8.10 (upgraded from 3.8.9 which works) but with Java not kotlin. Is there a recommended way to deal with this bug (except staying on 3.8.9)? Or should I rather create a separate issue? For me the issue is (debugged openapi processor) that context.getProjectDir() returns null

**Comment by altro3** [comment] 2023-08-19 06:03
@thalesdev I tested it today and I found  new bug - https://github.com/micronaut-projects/micronaut-core/issues/9746

Thats what I see, when tried to use all version with fixes:

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/28d7f869-27f3-452f-bc17-7637adefb9ae)

**Comment by altro3** [comment] 2023-08-19 07:46
@nbrugger-tgm If you have the similar problem with java - need to create another issue with example. But first, check, please, that you use latest micronaut-openapi version  - `4.10.0` - for micronaut 3 or `5.1.0` - for micronaut 4.

Also you can set project directory by property `micronaut.openapi.project.dir`, see documentation

**Comment by altro3** [comment] 2023-08-19 12:35
Ok, guys, I was still able to solve the last problem myself. I fixed it here: https://github.com/micronaut-projects/micronaut-openapi/pull/1173 Wait next release.

**Comment by altro3** [comment] 2023-08-25 11:40
I fixed last two bugs with KSP, but it will work correctly only with micronaut-core 4.2.0 - problems were in core module

**Comment by thalesdev** [comment] 2023-11-22 14:32
@altro3 any update about this issue?

**Comment by altro3** [comment] 2023-11-22 15:00
@thalesdev I can't merge it to master. I asked @graemerocher to do this, but as you see he still didn't do it

**Comment by altro3** [comment] 2023-11-22 15:01
I asked him in another PR about it

**Comment by altro3** [comment] 2023-11-24 14:58
Well, we finally managed to fix the problems with the KSP. Guys, please check. Some issues may not be fixed. Need to test on your projects

**Comment by bardale** [comment] 2023-12-05 10:48
Is this fixed?
I generated  [Kotlin app using Micronaut launch with openapi and swagger ui enabled](https://micronaut.io/launch?type=DEFAULT&name=swaggeruidemo&package=com.example&javaVersion=JDK_17&lang=KOTLIN&build=GRADLE_KOTLIN&test=SPOCK&features=swagger-ui&features=openapi&version=4.0.2)

Still I can see below error

```
> Task :kspKotlin
w: [ksp] C:/Users/XXXX/swaggeruidemo/src/main/kotlin/com/example/Application.kt:13: Unable to generate swagger.yml: C:\Users\XXXX\swaggeruidemo\build\generated\ksp\main\resources\META-INF\swagger\swaggeruid
emo-0.0.yml - C:\Users\XXXX\swaggeruidemo\build\generated\ksp\main\resources\META-INF\swagger\swaggeruidemo-0.0.yml.
C:\Users\XXXX\swaggeruidemo\build\generated\ksp\main\resources\META-INF\swagger\swaggeruidemo-0.0.yml
kotlin.io.FileAlreadyExistsException: C:\XXXX\Downloads\swaggeruidemo\build\generated\ksp\main\resources\META-INF\swagger\swaggeruidemo-0.0.yml
        at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:116)
        at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:67)
        at io.micronaut.kotlin.processing.visitor.KotlinVisitorContext$KspGeneratedFile.<init>(KotlinVisitorContext.kt:282)


```

**Comment by altro3** [comment] 2023-12-06 06:28
@bardale I chcked it: please, set latest version of micronaut openapi manually:

like this:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/359ebe4d-53c2-4dae-96bf-1b59d50f9f41)

Now micronaut platform 4.2.1 use version 6.1.0 - without KSP fix

**Closed by altro3** 2023-12-06 06:28 UTC
Labels: type: bug

**Comment by bardale** [comment] 2023-12-06 13:09
Thank you @altro3
